routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('articles.')->prefix('articles')->group(function() {
    Route::get('create',                'ArticleController@create')->name('create');
    Route::post('/',                    'ArticleController@store')->name('store');
    Route::get('{title}',               'ArticleController@show')->name('show');
    Route::get('{title}/edit',          'ArticleController@edit')->name('edit');
    Route::put('{title}',               'ArticleController@update')->name('update');
    Route::patch('auth/{user}',         'ArticleController@auth')->name('auth');
});
Route::post('preview',                  'ArticleController@preview');
Route::get('search/articles',           'ArticleController@search')->name('articles.search');

Route::get('images/{image}',            'ImageController@show')->name('images.show');
Route::post('images',                   'ImageController@store')->name('images.store');

Route::get('login',                     'Auth\LoginController@showLoginForm')->name('login');
Route::post('logout',                   'Auth\LoginController@logout')->name('logout');
Route::get('login/{provider}',          'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('user/auth',                 'UserController@auth')->name('user.auth');
Route::put('user/auth/{user}',          'UserController@changeRole');

Route::redirect('/', 'articles/home')->name('home');
Route::redirect('/home', 'articles/home');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>@yield('title', $article->title ?? '') - {{ env('APP_NAME', 'wiki.php') }}</title>
        <link rel="stylesheet" href="{{  asset('css/font-awesome.min.css') }}">
        <link rel="stylesheet" href="{{  asset('css/simplemde.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/app.css')}}" type="text/css">
        <link rel="stylesheet" href="{{ asset('css/prism.css')}}" type="text/css">
    </head>
    <body class="line-numbers bg-white">
        @include('partials.navbar')
        <div class="container">
            @yield('content')
        </div>
    </body>
    <script src="{{ asset('js/app.js') }}" defer></script>
    @stack('javascript')
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>@yield('title') - {{ env('APP_NAME', 'wiki.php') }}</title>
        <link rel="stylesheet" href="{{ asset('css/app.css')}}" type="text/css">
    </head>
    <body class="bg-white">
    <div class="container">
        <nav class="navbar navbar-expand-md">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav mr-auto">
                    <li class="nav-item">
                      @yield('back-link')
                    </li>
                </ul>
            </div>
        </nav>

        @yield('content')

    </div>
    </body>
    @stack('javascript')
</html>

resources/views/layouts/editor.blade.php
@extends('layouts.app')

@section('content')
{{-- 上傳進度 --}}
<div class="fixed-top">
    <p class="text-right d-none uploading notification"><img src="/img/loading.svg"> uploading...</p>
</div>

@yield('modal-alert', '')

<!-- Nav tabs -->
<ul class="nav nav-tabs mb-2" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="edit-tab" data-toggle="tab" href="#edit" role="tab" aria-controls="edit" aria-selected="true">@yield('tab-label')</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="preview-tab" data-toggle="tab" href="#preview" role="tab" aria-controls="preview" aria-selected="false">Preview</a>
  </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    {{-- 輸入 div --}}
    <div class="tab-pane edit active" id="edit" role="tabpanel" aria-labelledby="edit-tab">
        {{-- 條目標題 --}}
        <h1>{{ $article->title }}</h1>
        @yield('form')
            @csrf
            @yield('method-extra', '')

            @yield('hidden-article-id', '')

            {{-- 用隱藏欄位傳送條目標題，在 ArticleController@update 尋找 model Article --}}
            @include('layouts.hiddenArticleTitle', ['article' => $article])
            {{-- 工具列用來觸發檔案選擇的 <input type="file"> --}}
            @include('layouts.fileDialog')

            {{-- 如果 textarea 有縮排，會造成 markdown 轉 html 的第一行變成 <pre> --}}
            <textarea name="article[content]" id="editArticleContent" class="form-control" draggable="true">@yield('textarea-old-value', '')</textarea>
    </div>
    {{-- 預覽 div --}}
    <div class="tab-pane" id="preview" role="tabpanel" aria-labelledby="preview-tab">
        <h1>{{ $article->title }}</h1>
        <div class="preview markdown-body">
        </div>
    </div>

      <div class="form-inline mt-3">
        @section('btn-save-cancel')
        <button class="btn btn-primary">Save</button>
        <a class="btn" href="{{ route('articles.show', ['title' => $article->title]) }}">Cancel</a>
        @show
      </div>
    </form>
</div>
@endsection

@push('javascript')
    <script src="{{ asset('js/simplemde.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-native.min.js') }}" defer></script>
    <script src="{{ mix('js/edit.js')}}" defer></script>
@endpush

resources/views/layouts/fileDialog.blade.php
<input type="file" id="fileDialog" style="display:none" multiple accept="image/apng,image/bmp,image/gif,image/x-icon,image/jpeg,image/png,image/svg+xml,image/tiff,image/webp">

resources/views/layouts/hiddenArticleTitle.blade.php
<input type="hidden" name="article[title]" value="{{ $article->title }}">