routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('articles.')->prefix('articles')->group(function() {
    Route::get('create',                'ArticleController@create')->name('create');
    Route::post('/',                    'ArticleController@store')->name('store');
    Route::get('{title}',               'ArticleController@show')->name('show');
    Route::get('{title}/edit',          'ArticleController@edit')->name('edit');
    Route::put('{title}',               'ArticleController@update')->name('update');
    Route::patch('auth/{user}',         'ArticleController@auth')->name('auth');
});
Route::post('preview',                  'ArticleController@preview');
Route::get('search/articles',           'ArticleController@search')->name('articles.search');

Route::get('images/{image}',            'ImageController@show')->name('images.show');
Route::post('images',                   'ImageController@store')->name('images.store');

Route::get('login',                     'Auth\LoginController@showLoginForm')->name('login');
Route::post('logout',                   'Auth\LoginController@logout')->name('logout');
Route::get('login/{provider}',          'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('user/auth',                 'UserController@auth')->name('user.auth');
Route::put('user/auth/{user}',          'UserController@changeRole');

Route::redirect('/', 'articles/home')->name('home');
Route::redirect('/home', 'articles/home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use \Nicolaslopezj\Searchable\SearchableTrait;

    /**
     * Searchable rules.
     *
     * @var array
     */
    protected $searchable = [
        /**
         * Columns and their priority in search results.
         * Columns with higher values are more important.
         * Columns with equal values have equal importance.
         *
         * @var array
         */
        'columns' => [
            'articles.title' => 1,
        ]
    ];

        // 檢查是否有這個條目
    public static function exist($title) {
        return Article::where('title', $title)->count() > 0;
    }

    /**
     * 查詢關聯至條目的角色
     *
     * @return \App\Role
     */
    public function role() {
        return $this->belongsTo('App\Role');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use App\Role;
use App\Markdown\Markdown;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ArticleController extends Controller
{
    public function __construct() {
        $this->middleware('auth')->only(['auth']);
    }

    /**
     * 檢視條目
     */
    public function show($titleEncoded)
    {
        $title = rawurldecode($titleEncoded);
        $article = null;
        // 有這個條目
        if (Article::exist($title)) {
            $article        = Article::where('title', $title)->first();
            $article->exist = true;
        // 沒有這個條目
        } else {
            $article          = new \stdClass();
            $article->title   = $title;
            $article->content = '';
            $article->exist   = false;

            // 在 新增條目頁面 讀取 $title
            // 因爲路由是 GET /articles/create
            session()->put('articleTitle', $title);
        }

        // 把 markdown 語法轉成 HTML
        $article->body = Markdown::toHTML($article->content);
        $article->toc  = Markdown::toTOC($article->content);

        return view('articles.show')->with('article', $article);
    }

    /**
     * 編輯條目頁面
     */
    public function edit($titleEncoded)
    {
        $title = rawurldecode($titleEncoded);
        $article        = Article::where('title', $title)->first();
        $article->exist = true;

        // 合併 collection 和 eloquent collection 不容易
        // 直接用陣列比較簡單
        // 選項 anyone
        $option = [[
          'id' => 'anyone',
          'name' => 'Anyone',
        ]];
        // 再把表格 roles 的選項加進來
        $options = array_merge($option, Role::get()->toArray());

        // 決定 option selected
        // SQLite 使用整數 1 和 0 表示 true/false
        // 所以不用 === false，而是 == false
        if($article->is_restricted == false) {
            $options[0]['selected'] = 'selected';
        } else {
            $options[$article->role_id]['selected'] = 'selected';
        }
        // 顯示條目編輯頁面
        return view('articles.edit', [
            'article' => $article,
            'options' => $options,
        ]);
    }

    /**
     * 新增條目頁面
     */
    public function create() {
        $article        = new \stdClass();
        $article->title = session('articleTitle');
        $article->exist = false;

        return view('articles.create')->with('article', $article);
    }

    /**
     * 新增條目
     */
    public function store(Request $request) {
        $article          = new Article();
        $article->title   = $request->input('article.title');
        $article->content = $request->input('article.content');
        $article->save();

        // 刪除 新增條目頁面 的 session articleTitle
        session()->forget('articleTitle');

        return redirect()->route('articles.show',
                                 ['title' => $request->input('article.title')]);
    }
    /**
     * 更新條目
     */
    public function update($title, Request $request)
    {
        // 條目標題和內容
        $title = $request->input('article.title');

        $article          = Article::where('title', $title)->first();

        $this->authorize('update', $article);

        $article->content = $request->input('article.content');
        $article->save();

        // 跳轉到 檢示條目
        return redirect()->route('articles.show', ['title' => $title]);
    }

    /**
     * 預覽條目
     */
    public function preview(Request $request) {
        return Markdown::toHTML($request->post('markdown'));
    }

    /**
     * 條目權限
     */
    public function auth($articleId, Request $request) {
        $this->authorize('auth', Auth::user());

        DB::transaction(function () use ($articleId, $request) {
            $roleId = $request->input('roleId');
            $article = Article::findOrFail($articleId);

            if($roleId == 'anyone') {
                $article->is_restricted = false;
            } else {
                $article->is_restricted = true;
                $article->role_id = $roleId;
            }

            $article->save();
        });

        // 成功修改，回傳成功訊息
        return response()->json([
            'status' => 'success',
            'message' => 'Change role successfully',
        ]);
    }

    /**
     * 搜尋條目
     */
    public function search(Request $request) {
        $keyword = $request->query('keyword');

        // 如果關鍵字是空的，回到上一頁，不執行搜尋
        if(empty($keyword)) return back();

        $articles = Article::search($keyword)
                           ->orderBy('title', 'ASC')
                           ->paginate(25);

        return view('articles.search', [
            'keyword' => $keyword,
            'articles' => $articles,
        ]);
    }
}

resources/views/articles/create.blade.php
@extends('layouts.editor')

@section('tab-label', 'Create')

@section('form')
<form method="post" action="{{ route('articles.store') }}">
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.editor')

@section('tab-label', 'Edit')

@section('modal-alert')
    {{-- 權限控制確認對話框 --}}
    @include('partials.articles.auth-confirm-modal')
    {{-- 權限控制修改後的訊息列 --}}
    @include('partials.alert')
@endsection

@section('form')
<form action="{{ route('articles.update', ['title' => $article->title]) }}" method="post">
@endsection


@section('method-extra')
{{-- 更新資料，所以method=PUT --}}
@method('put')
@endsection

@section('hidden-article-id')
{{-- 執行權限控制需要抓取 $article->id --}}
<input type="hidden" name="article[id]" value="{{ $article->id }}">
@endsection

@section('textarea-old-value')
{{ old('article.content', $article->content) }}
@endsection


@section('btn-save-cancel')
{{-- 按鈕 Save, Cancel 和權限控制選單 --}}
    @can('update', $article)
    @parent
    @else
    <a href="{{ route('articles.show', ['title' => $article->title]) }}">back to {{ $article->title }}</a>
    @endcan

    @auth
    @if(Auth::user()->role->name == 'Administrator')
      @include('articles.partials.authorization-selection')
    @endif
    @endauth
@endsection

resources/views/articles/search.blade.php
@extends('layouts.app')

@section('title', 'Search ' . $keyword)

@section('content')
@inject('markdown', 'App\Markdown\MarkdownService')
@php use Illuminate\Support\Str; @endphp

@if($articles->count() == 0)
    @include('articles.partials.search-not-found')
@else
    @include('articles.partials.search-result')

    @include('articles.partials.search-result-pagination')
@endif
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row title">
    <h1>{{ $article->title }}</h1>

    <div class="ml-auto mt-2">
        @include('articles.partials.create-or-edit-button', [ 'article' => $article ])
    </div>
</div>

@if( ! $article->exist && $article->title == 'home' )
    @include('articles.partials.default-blank')
@else
<div class="row">
@include('articles.partials.markdown-render-result', [ 'article' => $article ])
@include('articles.partials.toc', [ 'article' => $article ])
</div>
@endif
@endsection

@push('javascript')
    <script src="{{ asset('js/prism.js')}}" defer></script>
@endpush